# Generated by Django 4.0.6 on 2022-08-03 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_password_profile_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
    ]
