# Generated by Django 4.0.6 on 2022-07-29 16:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='rentEnd',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='rentStart',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='type',
        ),
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('rentStart', models.DateField(blank=True, null=True)),
                ('rentEnd', models.DateField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.cart')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.product')),
            ],
        ),
    ]
