# Generated by Django 4.0.6 on 2022-07-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
