# Generated by Django 4.0.6 on 2022-07-29 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_cart_product_remove_cart_rentend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='rentEnd',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='rentStart',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='CartItems',
        ),
    ]
