# Generated by Django 4.0.6 on 2022-08-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_cart_product_remove_cart_rentend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
