# Generated by Django 4.0.6 on 2022-07-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rentDuration',
            field=models.CharField(blank=True, choices=[('per hr', 'Per Hour'), ('per day', 'Per Day')], max_length=10, null=True),
        ),
    ]
