# Generated by Django 4.0.6 on 2022-08-03 15:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_profile_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('rentStart', models.DateField(blank=True, null=True)),
                ('rentEnd', models.DateField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.cart')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.product')),
            ],
        ),
        migrations.DeleteModel(
            name='CartItems',
        ),
    ]
